### ISSUE TITLE
Add 'cross-spawn' to 'yargs-unparser' dependencies

### ISSUE THREAD

**Issue by p-racoon** [yargs/yargs-unparser#47]
Since 'yargs-unparser' is generally used along with '[yargs](https://github.com/yargs/yargs)', most people would never face this issue.
As '[cross-spawn](https://www.npmjs.com/package/cross-spawn)' is listed as devDependency in [yargs's package.json](https://github.com/yargs/yargs/blob/master/package.json).
But when using 'yargs-unparser' alone, it asks for ' [cross-spawn](https://www.npmjs.com/package/cross-spawn) ' 
and throws 
```
 ./node_modules/cross-spawn/index.js
Module not found: Can't resolve 'child_process' in '/path/to/project/ProjectName/node_modules/cross-spawn' 
```

**Comment by satazor** [comment]
@p-racoon I think this is not the case at all as the sole `index.js` file of this lib doesn’t use cross-spawn at all. The error you are experiencing should be coming from something else.

**Comment by p-racoon** [comment]
> @p-racoon I think this is not the case at all as the sole `index.js` file of this lib doesn’t use cross-spawn. The error you are experiencing should be coming from something else.

Yeah, after you pointed out I looked into 'yargs-unparser' source code it imports 'yargs' as well so this shouldn't be an issue. 

I am trying to use it with next.js, I think webpack could be the culprit here.

Even after separately importing 'cross-spawn' I received the error  
```
[ error ] ./node_modules/cross-spawn/index.js
Module not found: Can't resolve 'child_process' in '/home/prasham/Desktop/transform/node_modules/cross-spawn'
ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/home/prasham/Desktop/transform/node_modules/cross-spawn'
    at factory.create (/home/prasham/Desktop/transform/node_modules/next/node_modules/webpack/lib/Compilation.js:888:10)
    at factory (/home/prasham/Desktop/transform/node_modules/next/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
    at resolver (/home/prasham/Desktop/transform/node_modules/next/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/home/prasham/Desktop/transform/node_modules/next/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /home/prasham/Desktop/transform/node_modules/neo-async/async.js:2830:7
    at /home/prasham/Desktop/transform/node_modules/neo-async/async.js:6877:13
    at normalResolver.resolve (/home/prasham/Desktop/transform/node_modules/next/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/home/prasham/Desktop/transform/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/home/prasham/Desktop/transform/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/prasham/Desktop/transform/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/home/prasham/Desktop/transform/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/home/prasham/Desktop/transform/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/prasham/Desktop/transform/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/home/prasham/Desktop/transform/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/prasham/Desktop/transform/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/home/prasham/Desktop/transform/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
```

Sorry for the trouble. New to all this.
I understand this error is not related to `yargs-unparser` but, can you point out in which direction I should be looking, or what might be an issue here?

**Comment by satazor** [comment]
Try to run `npm ls cross-spawn` to see which module is using it in first place?

**Comment by p-racoon** [comment]
> Try to run `npm ls cross-spawn` to see which module is using it in first place.

Ran yarn equivalent of it which gives me this.
```
yarn list cross-spawn
yarn list v1.17.3
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ cross-spawn@6.0.5
├─ execa@0.7.0
│  └─ cross-spawn@5.1.0
└─ pretty-quick@1.11.1
   └─ cross-spawn@5.1.0
```
Definitely an issue from my side, Sorry for all this. 
Closing the issue.
Thanks a lot for the speedy help :smile: really appreciate it :blush:.

**Comment by satazor** [comment]
No problem @p-racoon, glad I could help. Good luck with your OSS journey, it was very insightful when I started and it still is.
